name: nvapp_mobile
description: "NvApp Mobile - Namaz Vakitleri Uygulaması"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  csv: ^6.0.0
  intl: ^0.19.0
  shared_preferences: ^2.3.2
  timezone: ^0.9.4
  flutter_local_notifications: ^17.2.2
  cupertino_icons: ^1.0.8
  url_launcher: ^6.2.5
  home_widget: ^0.7.0 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1" # Burası düzeldi
  flutter_lints: ^6.0.0

# İkon yapılandırması (Girintiler çok önemli!)
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png" # Arka planını sildiğin ikonu bu isimle kaydet
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/vakitler_corum.csv
    - assets/vakitler_nigde.csv
    - assets/vakitler_ankara.csv
